version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
